// Real flowition CLI output (status --json, events.jsonl) captured from scratch runs, for the tests.
export const statuses={"flo_prestart":"{\"runId\":\"flo_prestart\",\"state\":\"failed\",\"result\":{\"runId\":\"flo_prestart\",\"status\":\"failed\",\"error\":\"ENOENT: external-config.txt\"},\"phases\":[],\"agents\":[],\"steps\":[],\"questions\":[],\"live\":null}","flo_spend":"{\"runId\":\"flo_spend\",\"state\":\"completed\",\"result\":{\"runId\":\"flo_spend\",\"status\":\"completed\",\"result\":\"done\"},\"phases\":[],\"agents\":[{\"t\":2055,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"state\":\"done\",\"label\":\"worker\",\"adapter\":\"claude\",\"outputTokens\":300,\"lastOutputAt\":2050,\"usage\":{\"input\":100,\"output\":300,\"cost\":0.03}}],\"steps\":[],\"questions\":[],\"live\":null}"}
export const spendEvents="{\"t\":1000,\"type\":\"run\",\"runId\":\"flo_spend\",\"state\":\"started\",\"workflowFile\":\"/home/t/recoverable.workflow.mjs\"}\n{\"t\":1010,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"state\":\"queued\",\"label\":\"worker\",\"adapter\":\"claude\"}\n{\"t\":1020,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"state\":\"running\"}\n{\"t\":1050,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"state\":\"progress\",\"outputTokens\":1200,\"lastOutputAt\":1050}\n{\"t\":2000,\"type\":\"run\",\"runId\":\"flo_spend\",\"state\":\"resumed\",\"workflowFile\":\"/home/t/recoverable.workflow.mjs\"}\n{\"t\":2010,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"state\":\"queued\",\"label\":\"worker\",\"adapter\":\"claude\"}\n{\"t\":2020,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"state\":\"running\"}\n{\"t\":2050,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"state\":\"progress\",\"outputTokens\":300,\"lastOutputAt\":2050}\n{\"t\":2055,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"state\":\"done\",\"outputTokens\":300,\"usage\":{\"input\":100,\"output\":300,\"cost\":0.03},\"lastOutputAt\":2050}\n{\"t\":2060,\"type\":\"run\",\"runId\":\"flo_spend\",\"state\":\"completed\"}\n"
export const prestartEvent="{\"t\":1100,\"type\":\"run\",\"runId\":\"flo_prestart\",\"state\":\"failed\",\"error\":\"ENOENT: external-config.txt\"}\n"

export const liveStatus="{\"runId\":\"flo_a\",\"state\":\"running\",\"result\":null,\"phases\":[],\"agents\":[{\"t\":150,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"label\":\"old worker\",\"adapter\":\"codex\",\"state\":\"running\",\"outputTokens\":1200,\"lastOutputAt\":150}],\"steps\":[],\"questions\":[{\"t\":210,\"type\":\"question\",\"runId\":\"flo_a\",\"qid\":\"q0\",\"question\":\"Proceed?\",\"answered\":false}],\"live\":{\"id\":1,\"ok\":true,\"state\":\"running\",\"runId\":\"flo_a\",\"agents\":[],\"questions\":[{\"qid\":\"q0\",\"question\":\"Proceed?\"}],\"spentOutputTokens\":1200}}\n";
export const liveEvents="{\"t\":10,\"type\":\"run\",\"state\":\"started\",\"runId\":\"flo_a\",\"workflowFile\":\"/scratch/workflow.mjs\"}\n{\"t\":100,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"label\":\"old worker\",\"adapter\":\"codex\",\"state\":\"running\"}\n{\"t\":150,\"type\":\"agent\",\"index\":0,\"key\":\"k0\",\"state\":\"progress\",\"outputTokens\":1200,\"lastOutputAt\":150}\n{\"t\":200,\"type\":\"run\",\"state\":\"resumed\",\"runId\":\"flo_a\",\"workflowFile\":\"/scratch/workflow.mjs\"}\n{\"t\":210,\"type\":\"question\",\"runId\":\"flo_a\",\"qid\":\"q0\",\"question\":\"Proceed?\"}\n";

export const phaseStatus="{\"runId\":\"flo_a\",\"state\":\"running\",\"result\":null,\"phases\":[\"Approval\",\"Release\"],\"agents\":[],\"steps\":[],\"questions\":[],\"live\":null}\n"
export const phaseEvents="{\"t\":1000,\"type\":\"run\",\"runId\":\"flo_a\",\"state\":\"started\",\"workflowFile\":\"/w.mjs\",\"phases\":[{\"title\":\"Approval\"},{\"title\":\"Release\"}]}\n{\"t\":1500,\"type\":\"phase\",\"phaseIndex\":0,\"title\":\"Approval\"}\n{\"t\":2000,\"type\":\"phase\",\"phaseIndex\":1,\"title\":\"Release\"}\n{\"t\":3000,\"type\":\"run\",\"runId\":\"flo_a\",\"state\":\"failed\"}\n{\"t\":4000,\"type\":\"run\",\"runId\":\"flo_a\",\"state\":\"resumed\"}\n"

