#!/usr/bin/env node
// Emit `src/ui/tokens.css` from `src/ui/tokens.ts` — the single source of truth for the
// §3.2 color system.
//
//   npm run tokens
//
// A stylesheet cannot import a TypeScript module, so the token block is generated rather
// than hand-kept. `src/ui/tokens.test.ts` asserts the committed file is byte-identical to
// what this script would write, so a token edited in tokens.ts but not re-emitted fails
// CI instead of silently shipping a stale palette.
//
// It runs the TS through vite's esbuild-backed loader (a devDependency that is already
// present whenever anyone can run this script at all).

import { writeFileSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createServer } from 'vite'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const target = join(root, 'src', 'ui', 'tokens.css')

export const HEADER = `/* GENERATED by scripts/emit-tokens.mjs from src/ui/tokens.ts — do not edit by hand.
 *
 * DESIGN §3.2's OKLCH token system, with the nine W8a deviations (comps/README.md D1-D9)
 * the operator approved. Derived tokens stay live color-mix() calls so the anchor
 * technique is real at runtime: change --canvas and every surface follows.
 *
 * D1 (ruled to STAND): every mix interpolates \`in oklab\`, NOT \`in oklch\`. OKLCH walks
 * hue along an arc and the light theme's anchors are 160deg apart, which turns
 * --surface-selected into a pale green. src/ui/tokens.test.ts pins this.
 */
`

/** Build the file body the committed tokens.css must equal. */
export async function renderTokensCss() {
  const server = await createServer({
    root,
    configFile: false,
    logLevel: 'silent',
    server: { middlewareMode: true, watch: null },
  })
  try {
    const mod = await server.ssrLoadModule('/src/ui/tokens.ts')
    return `${HEADER}\n${mod.tokenCss()}\n`
  } finally {
    await server.close()
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const next = await renderTokensCss()
  const prev = (() => { try { return readFileSync(target, 'utf8') } catch { return null } })()
  if (prev === next) {
    console.log('src/ui/tokens.css already up to date')
  } else {
    writeFileSync(target, next)
    console.log(`wrote src/ui/tokens.css (${(next.length / 1024).toFixed(1)} KiB)`)
  }
}
